spring.application.name=rainmind

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=none

security.jwt.secret=adfasdfasdfasdfasdfasdfadfasdfasfsadfasfdsafsdfawcwesdfsadfwdsfasdfasdfasdfasdfasdfasdfasdfasdfsdfasfdfasdfasdfasdfasdfsdf
security.jwt.access-token-exp-ms=60

kma.auth-key=ac7485c0d0d65f53578be1bc44b46c69f93ef57074cecb63e0dad31c45925009

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}