CREATE TABLE IF NOT EXISTS shedlock
(
    name VARCHAR(64) PRIMARY KEY NOT NULL,
    locked_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    lock_until TIMESTAMP(6) NOT NULL,
    locked_by VARCHAR(256) NOT NULL
);